### ISSUE TITLE
j3dview giving an error when attempting to open the program.

### ISSUE THREAD

**Issue by KairosSMG** [RenolY2/j3dview#3]
I’ve used j3dview multiple times before but it randomly began giving me an error everytime I try to open it now. I’ve attached the error here I have no idea why it’s giving me this all of a sudden.

![image](https://github.com/RenolY2/j3dview/assets/77142293/4d0b7384-cff2-4b88-9738-010583bc1811)

**Comment by RenolY2** [comment]
Have you tried redownloading the tool? (in case any files important to the tool got lost somehow)

**Comment by KairosSMG** [comment]
I’ve tried redownloading and building the program myself but no matter what I do it gives me the same error. The only version that seems to work for me is the 0.4ver from blank63’s GitHub but that version does not have custom model support so I can’t use it.

**Comment by RenolY2** [comment]
If you tried to build it I guess you installed all the necessary dependencies. Then you can try running the program from source with python, j3dview.py is the main file to start the program.

Not sure why the compiled version crashes with the DLL error. Line 28 in j3dview points towards PyQt5 but that's supposed to be included. Wonder if some c++ runtime is missing or something.

**Comment by KairosSMG** [comment]
When running the program from source I get this error.

Traceback (most recent call last):
  File "C:\Users\Kairos\j3dview\j3dview.py", line 31, in <module>
    import gx
  File "C:\Users\Kairos\j3dview\gx\__init__.py", line 1, in <module>
    from gx.constants import *
  File "C:\Users\Kairos\j3dview\gx\constants.py", line 1141, in <module>
    class BlendSourceFactor(BlendFactor,metaclass=ExtendEnumMeta):
  File "C:\Users\Kairos\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 516, in __prepare__
    metacls._check_for_existing_members_(cls, bases)
  File "C:\Users\Kairos\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 962, in _check_for_existing_members_
    raise TypeError(
TypeError: <enum 'BlendSourceFactor'> cannot extend <enum 'BlendFactor'>

**Comment by RenolY2** [comment]
need to specifically run it with Python 3.5, it doesn't seem to work with later versions (I tried updating it for newer versions before but ran into issues that I couldn't solve because j3dview uses some programming concepts I don't fully understand)

The way I have it set up for j3dview, because I still need newer versions of Python, I just installed Python 3.5 without adding it to PATH, installed the necessary modules using pip in the Python 3.5 folder and created a .bat file that calls Python 3.5's exe on j3dview.py

**Comment by KairosSMG** [comment]
I have installed python3.5 but when I try to run j3dview.py I run into this error

Traceback (most recent call last):
  File "C:\Users\Kairos\j3dview\j3dview.py", line 32, in <module>
    import gx.bti
  File "C:\Users\Kairos\j3dview\gx\bti.py", line 3, in <module>
    import gx.texture
ImportError: No module named 'gx.texture'

How can I fix this as this is a module I think should be included in the source.

**Comment by RenolY2** [comment]
Ah, I forgot about this part of the tool. There are two lines in j3dview.py you'd have to uncomment and then you'd also have to have a specific version of Visual Studio installed to compile a .pyx file I think, but at the moment even I don't have that version installed so that also fails for me.
As a workaround, does it work if you download this file, unzip it and put it inside the gx folder?
[texture.cp35-win_amd64.pyd.zip](https://github.com/RenolY2/j3dview/files/15020628/texture.cp35-win_amd64.pyd.zip) should be the already compiled form of texture.pyx.

**Comment by KairosSMG** [comment]
Oh wow that fixed the issue! I am able to open the program now and run j3dview. Thank you so much for your help this issue has been really bothering me for the last week thanks for helping me resolve it!
